drivers: android: Kconfig: Samsung LMK changes depend on LMK
* lowmemorykiller was disabled in a previous commit which
  causes this build error so guard these changes properly.

mm/page_alloc.o: In function `__alloc_pages_nodemask':
page_alloc.c:(.text+0x543c): undefined reference to `timeout_lmk'